import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Soilmate Dashboard",
  description: "Generated by create next app",
};


import { Amplify } from "aws-amplify";
import ConfigureAmplifyClientSide from "../components/ConfigureAmplifyClientSide";
import config from "../amplifyconfiguration.json";
import { JSX } from "react";

Amplify.configure({ ...config }, { ssr: true });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html>
      <body>
        <ConfigureAmplifyClientSide />
        {children}
      </body>
    </html>
  );
}