import type { Metadata } from "next";
import "./globals.css";
import ConfigureAmplifyClientSide from "../components/ConfigureAmplifyClientSide";
import { JSX } from "react";

export const metadata: Metadata = {
  title: "Soilmate Dashboard",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html>
      <body>
        <ConfigureAmplifyClientSide />
        {children}
      </body>
    </html>
  );
}